accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .views import UserView, signup

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('profile/',  login_required(UserView.as_view()), name='profile'),
    path('signup/', signup, name='signup')
]

dxmain/urls.py
from django.contrib import admin
from django.urls import path
from . import views



urlpatterns = [
    path('', views.home, name="home"),
    path('services/', views.services, name="services"),
    path('contact/', views.contact, name="contact"),
    path('subscribe/', views.subscribe, name="subscribe"),
    path('success/', views.success, name="success"),
    path('success1/', views.success1, name="success1"),
]

dxtrades/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('dxmain.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('dasboard/', include('Balance.urls')),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>MXTRADE INVEST</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	
	<!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="#" />
	
	<!-- Favicon icon -->
    <link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-grad-school.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
	<!-- Chat Bot -->
	<!-- Smartsupp Live Chat script -->
<script type="text/javascript">
var _smartsupp = _smartsupp || {};
_smartsupp.key = '12937e696bcc1a443cfa8c91f9688cc535d47400';
window.smartsupp||(function(d) {
  var s,c,o=smartsupp=function(){ o._.push(arguments)};o._=[];
  s=d.getElementsByTagName('script')[0];c=d.createElement('script');
  c.type='text/javascript';c.charset='utf-8';c.async=true;
  c.src='https://www.smartsuppchat.com/loader.js?';s.parentNode.insertBefore(c,s);
})(document);
</script>
  </head>

<body>

   
  <!--header-->
  <header class="main-header clearfix" role="header">
    <div class="logo">
      <a href="{% url 'home' %}" style="font-size: 100%;"><em>MXTRADE</em> INVEST</a>
    </div>
	{% if user.is_authenticated %}
		<a href="#" class="menu-link"><i class="fa fa-bars"></i></a>
		<nav id="menu" class="main-nav" role="navigation">
		  <ul class="fu">
			<li><a href="{% url 'users:profile' %}">Hello, <span><i class="fa fa-user" style=""></i></span>   {{user.first_name}}</a></li>
			<li><a href="{% url 'home' %}"><i class="fa fa-home"></i></a></li>
			<li><a href="#"><i class="fa fa-info"></i></a></li>
			<li><a href="{% url 'wallet' %}"><i class="fa fa-dashboard"></i></a></li>
			<li><a href="{% url 'users:logout' %}"><i class="fa fa-sign-out"></i></a></li>
		  </ul>
		</nav>
	{% else %}
		<a href="#" class="menu-link"><i class="fa fa-bars"></i></a>
		<nav id="menu" class="main-nav" role="navigation">
		  <ul class="fu">
			<li><a href="{% url 'home' %}"><i class="fa fa-home"></i></a></li>
			<li><a href=""><i class="fa fa-info"></i></a></li>
			<li><a href="{% url 'users:login' %}"><i class="fa fa-sign-in"></i></a></li>
			<li><a href="{% url 'users:signup' %}">Register</a></li>
		  </ul>
		</nav>
	{% endif %}
	<div id="menu" class="main-nav menu-link clearfix" style="height:62px; background-color: #1D2330; overflow:hidden; box-sizing: border-box; border: 1px solid #282E3B; border-radius: 4px; text-align: right; line-height:14px; block-size:62px; font-size: 12px; font-feature-settings: normal; text-size-adjust: 100%; box-shadow: inset 0 -20px 0 0 #262B38;padding:1px;padding: 0px; margin: 0px; width: 100%;" role="header">
		<div style="height:40px; padding:0px; margin:0px; width: 100%;">
			<iframe src="https://widget.coinlib.io/widget?type=horizontal_v2&theme=dark&pref_coin_id=1505&invert_hover=no" width="100%" height="36px" scrolling="auto" marginwidth="0" marginheight="0" frameborder="0" border="0" style="border:0;margin:0;padding:0;">
			</iframe>
		</div>
		<div style="color: #626B7F; line-height: 14px; font-weight: 400; font-size: 11px; box-sizing: border-box; padding: 2px 6px; width: 100%; font-family: Verdana, Tahoma, Arial, sans-serif;">
		</div>
	</div>
	
  </header>

  {% block content %}
  
  {% endblock %}
 

	<section class="section" style="background-color: #172238; text-align:center;">
		<div class="container" style="background-repeat: no-repeat;    background-size: cover;    background-color: #172238;">
			<div class="row align-self-center">
				<div class="col-md-12" style="font-size:15px; font-weight:10px;">
						<i class="fa fa-envelope" style="color:white;"></i><a href="mailto:mxtradeinvest@outlook.com" style="padding-right:10px;" rel="sponsored" target="_parent"> Mxtradeinvest@outlook.com     </a>

						<i class="fa fa-whatsapp" style="color:white;"></i><a href="https://wa.me/message/RYMEH5BTKKEBE1" rel="sponsored" target="_parent"> WhatsApp</a>
				</div>
			</div>
		</div>
	</section>


	
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p><i class="fa fa-copyright"></i> Copyright 2020 by <a href="" rel="sponsored" target="_parent">MxTrade</a></p>
        </div>
      </div>
    </div>
  </footer>
 

  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/isotope.min.js' %}"></script>
    <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
    <script src="{% static 'assets/js/lightbox.js' %}"></script>
    <script src="{% static 'assets/js/tabs.js' %}"></script>
    <script src="{% static 'assets/js/video.js' %}"></script>
    <script src="{% static 'assets/js/slick-slider.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .scroll-to-section').on('click', 'a', function (e) {
          if($(e.target).hasClass('external')) {
            return;
          }
          e.preventDefault();
          $('#menu').removeClass('active');
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>
</body>
</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head> 
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<!-- Primary Meta Tags -->
	<title>Maximum Trade Investments - Your financial solution</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="title" content="Maximum Trade Investments - Your financial solution">
	<meta name="author" content="Natixis">
	<meta name="description" content="Maximum Trade Investments - Mx trade invest is a professional trading and investment company emphasis on cryptocurrency, forex trading and stock market stability.">
	<link rel="canonical" href="">

	<!-- Open Graph / Facebook -->
	<meta property="og:type" content="website">
	<meta property="og:url" content="">
	<meta property="og:title" content="Maximum Trade Investments - Your financial solution">
	<meta property="og:description" content="Maximum Trade Investments - Mx trade invest is a professional trading and investment company emphasis on cryptocurrency, forex trading and stock market stability.">
	<meta property="og:image" content="">

	<!-- Twitter -->
	<meta property="twitter:card" content="summary_large_image">
	<meta property="twitter:url" content="">
	<meta property="twitter:title" content="Maximum Trade Investments - Your financial solution">
	<meta property="twitter:description" content="Maximum Trade Investments - Mx trade invest is a professional trading and investment company emphasis on cryptocurrency, forex trading and stock market stability.">
	<meta property="twitter:image" content="">

	<!-- Favicon -->
	<link rel="apple-touch-icon" sizes="120x120" href="{% static 'assets/images/favicon.ico' %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'assets/images/favicon.ico' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicon.ico' %}">
	<link rel="manifest" href="{% static 'assets/images/favicon.ico' %}">
	<link rel="mask-icon" href="{% static 'assets/images/favicon.ico' %}" color="#ffffff">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="theme-color" content="#ffffff">

	<!-- Fontawesome -->
	<link type="text/css" href="{% static 'ffs/vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

	<!-- Notyf -->
	<link type="text/css" href="{% static 'ffs/vendor/notyf/notyf.min.css' %}" rel="stylesheet">

	<!-- Volt CSS -->
	<link type="text/css" href="{% static 'ffs/css/volt.css' %}" rel="stylesheet">

	<!-- NOTICE: You can use the _analytics.html partial to include production code specific code & trackers -->

 </head>

<body>

	<nav class="navbar navbar-dark navbar-theme-primary px-4 col-12 d-md-none">
		<a href="{% url 'home' %}" class="navbar-brand mr-lg-5" style="font-size: 100%;"><span sytle="color:orange;">MXTRADE</span> INVEST</a>
		<div class="d-flex align-items-center">
			<button class="navbar-toggler d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
		</div>
	</nav>

	<div class="container-fluid bg-soft">
		<div class="row">
			<div class="col-12">

				<nav id="sidebarMenu" class="sidebar d-md-block bg-primary text-white collapse" data-simplebar>
					<div class="sidebar-inner px-4 pt-3">
						<div class="user-card d-flex d-md-none align-items-center justify-content-between justify-content-md-center pb-4">
							<div class="d-flex align-items-center">
								<div class="user-avatar lg-avatar mr-4" style="color:#000000;">
									<span class="fas fa-user" style="color:#000000;"></span>
								</div>
								<div class="d-block">
									<h2 class="h6">Hi, {{ user.first_name }}</h2>
									<a href="{% url 'users:logout' %}" class="btn btn-secondary text-dark btn-xs"><span class="mr-2"><span class="fas fa-sign-out-alt"></span></span>Sign Out</a>
								</div>
							</div>
							<div class="collapse-close d-md-none">
								<a href="#sidebarMenu" class="fas fa-times" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="true" aria-label="Toggle navigation"></a>
							</div>
						</div>
						<ul class="nav flex-column">
							<li class="nav-item">
							  <a href="{% url 'home' %}" class="nav-link">
								<span class="sidebar-icon"><span class="fas fa-home"></span></span>
								<span>Homepage</span>
							  </a>
							</li>
							<li class="nav-item  {% block active %}{% endblock %} ">
							  <a href="{% url 'wallet' %}" class="nav-link">
								<span class="sidebar-icon"><span class="fas fa-chart-pie"></span></span>
								<span>Dashboard</span>
							  </a>
							</li>
							<li class="nav-item {% block activee %} {% endblock %} ">
							  <a href="{% url 'transaction' %}" class="nav-link">
								  <span class="sidebar-icon"><span class="fas fa-chart-line"></span></span>
								  <span>Transactions</span>
							  </a>
							</li>
							<li class="nav-item">
							  <a href="{% url 'deposit' %}" class="nav-link">
								  <span class="sidebar-icon"><span class="fas fa-hand-holding-usd"></span></span>
								  <span>Deposit</span>
							  </a>
							</li>
							<li class="nav-item">
							  <a href="{% url 'withdraw' %}" class="nav-link">
								  <span class="sidebar-icon"><span class="fas fa-dollar-sign"></span></span>
								  <span>Withdraw</span>
							  </a>
							</li>														
							<li class="nav-item {% block activeee %}{% endblock %}">

							  <a href="{% url 'users:profile' %}" class="nav-link">
								  <span class="sidebar-icon"><span class="fas fa-cog"></span></span>
								  <span>Settings</span>
							  </a>
							</li>
							<li class="nav-item">
							  <a href="{% url 'users:logout' %}" class="nav-link">
								  <span class="sidebar-icon"><span class="fas fa-sign-out-alt"></span></span>
								  <span>Logout</span>
							  </a>
							</li>
							
						</ul>
					</div>
				</nav>

                
				<main class="content">

					<nav class="navbar navbar-top navbar-expand navbar-dashboard navbar-dark pl-0 pr-2 pb-0">
						<div class="container-fluid px-0">
						  <div class="d-flex justify-content-between w-100" id="navbarSupportedContent">
									
							<!-- Navbar links -->
							<ul class="navbar-nav align-items-center">
							  
							  <li class="nav-item dropdown">
								<a class="nav-link pt-1 px-0" href="{% url 'users:profile' %}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								  <div class="media d-flex align-items-right">
									<span class="fas fa-user fa-pull-right" style="color:black;"><a href="{% url 'users:profile' %}"></a></span>
									<div class="media-body ml-2 text-dark align-items-right d-none d-lg-block">
									  <span class="mb-0 font-small font-weight-bold">Hi, <uppercase><b>{{ user.first_name }}</b></uppercase></span>
									</div>
								  </div>
								</a>
							  </li>
							</ul>
						  </div>
						</div>
					</nav>
					{% block content %}
					
					{% endblock %}
					
					
                        <footer class="footer section py-5">

						<div class="row">
							<div class="col-12 col-lg-6 mb-4 mb-lg-0">
								<p class="mb-0 text-center text-xl-left">Copyright © <span class="current-year"></span> <br><a class="text-primary font-weight-normal" href="{% url 'home' %}" target="_blank">Maximum Trade Investments</a></p>
							</div>
						</div>
					</footer>
                    </main>
                </div>
            </div>
        </div>

    		<!-- Core -->
		<script src="{% static 'ffs/vendor/popper.js/dist/umd/popper.min.js' %}"></script>
		<script src="{% static 'ffs/vendor/bootstrap/dist/js/bootstrap.min.js' %}"></script>

		<!-- Vendor JS -->
		<script src="{% static 'ffs/vendor/onscreen/dist/on-screen.umd.min.js' %}"></script>

		<!-- Slider -->
		<script src="{% static 'ffs/vendor/nouislider/distribute/nouislider.min.js' %}"></script>

		<!-- Jarallax -->
		<script src="{% static 'ffs/vendor/jarallax/dist/jarallax.min.js' %}"></script>

		<!-- Smooth scroll -->
		<script src="{% static 'ffs/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>

		<!-- Count up -->
		<script src="{% static 'ffs/vendor/countup.js/dist/countUp.umd.js' %}"></script>

		<!-- Notyf -->
		<script src="{% static 'ffs/vendor/notyf/notyf.min.js' %}"></script>

		<!-- Charts -->
		<script src="{% static 'ffs/vendor/chartist/dist/chartist.min.js' %}"></script>
		<script src="{% static 'ffs/vendor/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js' %}"></script>

		<!-- Datepicker -->
		<script src="{% static 'ffs/vendor/vanillajs-datepicker/dist/js/datepicker.min.js' %}"></script>

		<!-- Simplebar -->
		<script src="{% static 'ffs/vendor/simplebar/dist/simplebar.min.js' %}"></script>

		<!-- Github buttons -->
		<script async defer src="https://buttons.github.io/buttons.js"></script>

		<!-- Volt JS -->
		<script src="{% static 'ffs/assets/js/volt.js' %}"></script>

	</body>

</html>

templates/deposit.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}


        <!-- Section -->
        <section class="vh-lg-100 d-flex align-items-center">
            <div class="container">
                <div class="row justify-content-center form-bg-image">
                    <div class="col-12 d-flex align-items-center justify-content-center">
                        <div class="signin-inner my-3 my-lg-0 bg-white shadow-soft border rounded border-light p-4 p-lg-5 w-100 fmxw-500">
                            <div class="text-center text-md-center mb-4 mt-md-0">
                                <h1 class="mb-0 h3">Deposit</h1>
                            </div>
							
                            <form action="" method="POST" class="mt-4">
							{% csrf_token %}
                                <!-- Form -->
                                <div class="form-group mb-4">
                                    <div class="input-group">
                                        <span class="input-group-text" id="basic-addon1"><span class="fas fa-envelope"></span></span>
                                        <input type="email" name="email" class="form-control" placeholder="example@company.com" id="email" autofocus required>
                                    </div>  
                                </div>
                                <!-- End of Form -->
                                <div class="form-group">
                                    <!-- Form -->
                                    <div class="form-group mb-4">
                                        <div class="input-group">
                                            <span class="input-group-text" id="basic-addon2"><span class="fas fa-wallet"></span></span>
                                            <input type="text" name="asset" placeholder="Amount in USD" class="form-control" id="password" required>
                                        </div>  
                                    </div>
                                    <!-- End of Form -->
                                <button type="submit" class="btn btn-block btn-primary">Next</button>
                            </form>
                            <div class="d-flex justify-content-center align-items-center mt-4">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>


{% endblock %}

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <title>MXTRADE INVEST</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
	
	<!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="#" />
	
	<!-- Favicon icon -->
    <link rel="icon" href="{% static 'assets/images/favicon.ico' %}" type="image/x-icon">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/templatemo-grad-school.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
	<!-- Chat Bot -->
	<!-- Smartsupp Live Chat script -->
<script type="text/javascript">
var _smartsupp = _smartsupp || {};
_smartsupp.key = '12937e696bcc1a443cfa8c91f9688cc535d47400';
window.smartsupp||(function(d) {
  var s,c,o=smartsupp=function(){ o._.push(arguments)};o._=[];
  s=d.getElementsByTagName('script')[0];c=d.createElement('script');
  c.type='text/javascript';c.charset='utf-8';c.async=true;
  c.src='https://www.smartsuppchat.com/loader.js?';s.parentNode.insertBefore(c,s);
})(document);
</script>
  </head>

<body>

<section class="section coming-soon" data-section="section3">
    <div class="container">
		<div class="row">
			<div class="col-md-7 col-xs-12">
				<div class="continer centerIt">
					<div>
						<h4>Sign In <em>Here</em> and start enjoying <em>Unlimited</em> Offers</h4>
						<p style="color: white;">Latest <em>Promos & Bonuses </em>Available</p>
						<div class="counter">

						<div class="days">
							<div class="value">00</div>
							<span>Days</span>
						</div>

						<div class="hours">
							<div class="value">00</div>
							<span>Hours</span>
						</div>

						<div class="minutes">
						  <div class="value">00</div>
						  <span>Minutes</span>
						</div>

						<div class="seconds">
						  <div class="value">00</div>
						  <span>Seconds</span>
						</div>

					</div>
				</div>
			</div>
        </div>
        <div class="col-md-5">
			<div class="right-content">
				<div class="top-content">
					<h6 style="font-size:30px;"><b>Sign In</h6>
				</div>
				<form id="contact" action="" method="post">
				{% csrf_token %}
					<!--
					<div class="row">
						<div class="col-md-12">
						  <fieldset>
							<input name="username" type="text" class="form-control" id="username" placeholder="Username" required="True">
						  </fieldset>
						</div>
						<div class="col-md-12">
						  <fieldset>
							<input name="password" type="text" class="form-control" id="password" placeholder="Password" required="True">
						  </fieldset>
						</div>
						-->
						<div class="row">
							<div class="col-md-12">
								{{ form.as_p }}
								<div class="col-md-12 bb">
									<fieldset>
										<button type="submit" id="form-submit" class="button">Login</button>
									</fieldset>
								</div>
					  <div class="col-md-12">
						<fieldset>
						  <p class="button" style="color: white;">Don't have an account?<a href="{% url 'users:signup' %}"> SignUp</a></p>
						</fieldset>
					  </div>
					</div>
				</form>
			</div>
        </div>
		
	</div>
	
</section>

		<footer>
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p><i class="fa fa-copyright"></i> Copyright 2020 by <a href="{% url 'home' %}" rel="sponsored" target="_parent">MxTrade</a></p>
					</div>
				</div>
			</div>
		</footer>



 

  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/js/isotope.min.js' %}"></script>
    <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
    <script src="{% static 'assets/js/lightbox.js' %}"></script>
    <script src="{% static 'assets/js/tabs.js' %}"></script>
    <script src="{% static 'assets/js/video.js' %}"></script>
    <script src="{% static 'assets/js/slick-slider.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script>
        //according to loftblog tut
        $('.nav li:first').addClass('active');

        var showSection = function showSection(section, isAnimate) {
          var
          direction = section.replace(/#/, ''),
          reqSection = $('.section').filter('[data-section="' + direction + '"]'),
          reqSectionPos = reqSection.offset().top - 0;

          if (isAnimate) {
            $('body, html').animate({
              scrollTop: reqSectionPos },
            800);
          } else {
            $('body, html').scrollTop(reqSectionPos);
          }

        };

        var checkSection = function checkSection() {
          $('.section').each(function () {
            var
            $this = $(this),
            topEdge = $this.offset().top - 80,
            bottomEdge = topEdge + $this.height(),
            wScroll = $(window).scrollTop();
            if (topEdge < wScroll && bottomEdge > wScroll) {
              var
              currentId = $this.data('section'),
              reqLink = $('a').filter('[href*=\\#' + currentId + ']');
              reqLink.closest('li').addClass('active').
              siblings().removeClass('active');
            }
          });
        };

        $('.main-menu, .scroll-to-section').on('click', 'a', function (e) {
          if($(e.target).hasClass('external')) {
            return;
          }
          e.preventDefault();
          $('#menu').removeClass('active');
          showSection($(this).attr('href'), true);
        });

        $(window).scroll(function () {
          checkSection();
        });
    </script>
</body>
</html>

templates/transaction.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}

<div class="row">
	<div class="col-12 col-xl-12 mb-4">
		<div class="row">
			<div class="col-12 mb-4">
				<div class="card border-light shadow-sm">

					<div class="table-responsive">
						<table class="table align-items-center table-flush">
							<thead class="thead-light">
								<tr>
									<th scope="col">ID</th>
									<th scope="col">Date Created</th>
									<th scope="col">Amount</th>
									<th scope="col">Type</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<th scope="row">
										{{user.transaction.user}}
									</th>
									<td>
										{{ user.transaction.created }}
									</td>
									<td>
										${{ user.transaction.amount }}
									</td>
									<td>
										<span class="fas fa-arrow-up text-danger mr-3"></span> {{ user.transaction.tp }}
									</td>
									</tr>
									<tr>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}